name: Build and deploy to gh pages with Trunk

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - uses: jetli/trunk-action@v0.1.0
      - uses: jetli/wasm-bindgen-action@v0.1.0
      - uses: actions/checkout@v2
      - run: trunk build --release
      - uses: actions/upload-pages-artifact@v2
        with:
          path: dist

  deploy:
    runs-on: ubuntu-latest

    needs: build

    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/deploy-pages@v2
        id: deployment
